apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-v2
  labels:
    app: login-app
    version: v2
spec:
  selector:
    matchLabels:
      app: login-app
      version: v2
  template:
    metadata:
      labels:
        app: login-app
        version: v2
    spec:
      containers:
        - name: login-container-v2
          image: nginxstore/example-login-ui:v2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login-svc-v2
spec:
  selector:
    app: login-app
    version: v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
